<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_billing_first_name</name>
   <tag></tag>
   <elementGuidId>20d01488-5447-4c7a-9986-9e2b50f5bb71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_first_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_first_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c5e465d-1618-44c4-91b8-8030dd278e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a52e803b-dbba-4950-a5ba-8664d05ecc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>0c33b71d-f39c-4f2e-94e9-345d186fae94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_first_name</value>
      <webElementGuid>d0c3b1e3-354b-4a90-8999-e68af90ba890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_first_name</value>
      <webElementGuid>10f6deca-8be8-4e0a-9e11-a5e1531b5156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>d8e8104d-a41b-4ded-8873-b707bf4f8dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_first_name&quot;)</value>
      <webElementGuid>0a2d4038-d6ca-4809-9da0-927e32aa031e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_first_name']</value>
      <webElementGuid>0bc705e2-80cd-4ff1-a96e-ad29230c131c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_first_name_field']/span/input</value>
      <webElementGuid>216b922b-e9d0-445e-9f05-9ff532241372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>2cd1b5c6-ebe4-4564-a1b1-49c660c888e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_first_name' and @id = 'billing_first_name']</value>
      <webElementGuid>c171aff9-215e-4ec8-be9f-9ee122e7310d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
