<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_zoomImg</name>
   <tag></tag>
   <elementGuidId>d1db6b94-6dec-4cb1-9726-44495d65bd5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-54']/div/div/figure/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.zoomImg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>66393307-25fc-4634-b400-16f2e9328004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e8a43ebe-13d8-484c-8b32-646de0fd8086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up.jpg</value>
      <webElementGuid>4a98511e-cbc4-4a79-864e-c1a81e856c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zoomImg</value>
      <webElementGuid>8013e66a-1aa4-404d-a9c7-d53e81fc3faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-54&quot;)/div[@class=&quot;woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-4 images&quot;]/div[@class=&quot;flex-viewport&quot;]/figure[@class=&quot;woocommerce-product-gallery__wrapper&quot;]/div[@class=&quot;woocommerce-product-gallery__image flex-active-slide&quot;]/img[@class=&quot;zoomImg&quot;]</value>
      <webElementGuid>d18a42c3-d4e9-4e57-97b6-a624a78f3e2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-54']/div/div/figure/div/img</value>
      <webElementGuid>97867df2-28ff-43ab-9367-681c58c87a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up.jpg')]</value>
      <webElementGuid>a726f518-f76f-4af3-924e-97d126df63a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>e2f3ae30-1949-42f4-9988-9837c81a462d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up.jpg']</value>
      <webElementGuid>c57663ac-a0e2-4083-83e7-286144aea279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
