<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>All Kotak Drop Down</name>
   <tag></tag>
   <elementGuidId>3de806e5-4b70-4810-b7cb-897fe262ccdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-levelAdd-results']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-levelAdd-results</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>cff88dad-b49f-47fd-ac15-2be9eef25423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>03b3c4d4-e17e-4cf7-b33a-49c46c47e25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tree</value>
      <webElementGuid>ec0a0e43-6870-451f-abee-460f19c4fbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-levelAdd-results</value>
      <webElementGuid>bf2e3ac0-03fe-4170-8db2-b92318e0c1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3091689b-dbd7-4b4e-bf94-0faef4cfff40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>23486e53-3dff-4253-b8ee-d2b3539cd845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ISOLevel 1Level 1Level 2Level 2Materi 1Materi 2Materi 3Materi 4</value>
      <webElementGuid>b255311c-023d-490d-a10d-1cdcecbec464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-levelAdd-results&quot;)</value>
      <webElementGuid>6c867b7c-0c89-4c2f-9f73-a1ca1ff87223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-levelAdd-results']</value>
      <webElementGuid>e4ee4be0-27da-4aa2-a58c-92bfbaa2e4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/span/span/span[2]/ul</value>
      <webElementGuid>bb4e8609-4bb8-48a2-88d7-a2d71d663aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>df437c78-eadc-4ff8-81df-7da0f3cf40b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-levelAdd-results' and (text() = 'ISOLevel 1Level 1Level 2Level 2Materi 1Materi 2Materi 3Materi 4' or . = 'ISOLevel 1Level 1Level 2Level 2Materi 1Materi 2Materi 3Materi 4')]</value>
      <webElementGuid>8614a38d-ab6c-4226-bb73-9689406fb3a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
