<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_optD</name>
   <tag></tag>
   <elementGuidId>faf3fce9-2cb0-4fa2-8cae-ed2546f96e9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='optDAdd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#optDAdd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8f2a2efd-debc-4b31-9af2-af2cfa4af320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e631d859-0e93-416d-a6ae-53ed3ea05735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optD</value>
      <webElementGuid>90ac5135-f385-45c4-a351-2c4f6b1dd2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optDAdd</value>
      <webElementGuid>d056355e-d82f-4ab2-a823-902574d915e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d52a9ea1-9136-4ec2-9a48-9337bd015571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Option D</value>
      <webElementGuid>cdd7eb5c-7aec-474b-9a3c-de31605f2f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>a1830b07-ab8d-41b3-9729-3060824a5fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optDAdd&quot;)</value>
      <webElementGuid>416d0b15-99c0-40b3-9029-301b47f62352</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='optDAdd']</value>
      <webElementGuid>f0ea40b5-ce17-40c3-a53b-e2adfbf262cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[4]/div[2]/div/textarea</value>
      <webElementGuid>1886793c-8aa7-493d-b55e-316e0e96dabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/textarea</value>
      <webElementGuid>bda06e33-52cd-41c6-bcd0-306d67a180ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'optD' and @id = 'optDAdd' and @placeholder = 'Option D']</value>
      <webElementGuid>dd920c99-aad6-46e7-9f38-60f36e487df3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
